# Form implementation generated from reading ui file '.\ui\company_card.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(480, 581)
        Frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(parent=Frame)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.image = QtWidgets.QLabel(parent=Frame)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.contribution = QtWidgets.QLabel(parent=Frame)
        self.contribution.setObjectName("contribution")
        self.verticalLayout.addWidget(self.contribution, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.name.setText(_translate("Frame", "TextLabel"))
        self.image.setText(_translate("Frame", "TextLabel"))
        self.contribution.setText(_translate("Frame", "TextLabel"))
